[custom]

;规则
ruleset=DIRECT,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/privateip.list
ruleset=DIRECT,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/private.list
ruleset=DIRECT,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/fakeip-filter.list
ruleset=🚫 拦截访问,https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockmihomolite.yaml
ruleset=🎯 直连访问,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/googlefcm.list
ruleset=🎯 直连访问,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/games-cn.list
ruleset=🎯 直连访问,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/apple-cn.list
ruleset=🎯 直连访问,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/networktest.list
ruleset=🪩 Cloudflare,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/cloudflare.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/microsoft.list
ruleset=✈️ Telegram,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/telegram.list
ruleset=🐦 Twitter,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geosite/twitter.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/tiktok.list
ruleset=✈️ Telegram,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/telegramip.list
ruleset=🐦 Twitter,https://raw.githubusercontent.com/appshubcc/bett-rules/meta/geo/geoip/twitterip.list
ruleset=🍀 Google,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/gfw.list
ruleset=🍀 Google,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/proxy.list
ruleset=🎯 直连访问,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/cn.list
ruleset=🎯 直连访问,https://raw.githubusercontent.com/DustinWin/ruleset_geodata/mihomo-ruleset/cnip.list
ruleset=🎯 直连访问,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

;策略组
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=♻️ 自动选择`url-test`.*`https://www.gstatic.com/generate_204`600,,50
custom_proxy_group=☁️ 故障转移`fallback`.*`https://www.gstatic.com/generate_204`600,,50
custom_proxy_group=🖲️ 手动选择`select`.*`[]DIRECT
custom_proxy_group=🔮 负载均衡`load-balance`.*`https://www.gstatic.com/generate_204`600,,50
custom_proxy_group=🍀 Google`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=🪩 Cloudflare`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=🪟 Microsoft`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=✈️ Telegram`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=🐦 Twitter`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=🎵 TikTok`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问

custom_proxy_group=🇭🇰 香港节点`url-test`(?i)(港|hk|hongkong|hong kong|🇭🇰)`https://www.gstatic.com/generate_204`600,,50
custom_proxy_group=🇹🇼 台湾节点`url-test`(?i)(台|新北|彰化|tw|taiwan|🇹🇼)`https://www.gstatic.com/generate_204`600,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(?i)(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|jp|japan|🇯🇵)`https://www.gstatic.com/generate_204`600,,50
custom_proxy_group=🇺🇸 美国节点`url-test`(?i)(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|us|unitedstates|united states|🇺🇸)`https://www.gstatic.com/generate_204`600,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(?i)(新加坡|坡|狮城|sg|singapore|🇸🇬)`https://www.gstatic.com/generate_204`600,,50
custom_proxy_group=🇺🇳 其它地区`url-test`(?i)(🇭🇰|🇹🇼|🇯🇵|🇺🇸|🇸🇬|🇨🇳|🇰🇷|港|hk|hongkong|台|新北|彰化|tw|taiwan|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|jp|japan|新加坡|坡|狮城|sg|singapore|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|us|united states)`https://www.gstatic.com/generate_204`600,,50

custom_proxy_group=🎯 直连访问`url-test`[]DIRECT`[]REJECT`https://connectivitycheck.platform.hicloud.com/generate_204`600,,50
custom_proxy_group=🚫 拦截访问`select`[]REJECT`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]REJECT

;启用规则集
enable_rule_generator=true
;覆盖原有规则
overwrite_original_rules=true

;基础配置
;clash_rule_base=https://raw.githubusercontent.com/some6508/run/master/store/mihomo.yaml
