[custom]

;规则
ruleset=DIRECT,clash-ipcidr:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/privateip.mrs,86400
ruleset=DIRECT,clash-domain:https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs,86400
ruleset=DIRECT,clash-domain:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/fakeip-filter.mrs,86400
ruleset=🚫 拦截访问,clash-domain:https://cdn.jsdelivr.net/gh/217heidai/adblockfilters@main/rules/adblockmihomo.mrs,86400
ruleset=🎯 直连访问,clash-domain:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/networktest.mrs,86400
ruleset=🎯 直连访问,clash-domain:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/games-cn.mrs,86400
ruleset=🎯 直连访问,clash-domain:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/apple-cn.mrs,86400
ruleset=✈️ Telegram,clash-domain:https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.mrs,86400
ruleset=✈️ Telegram,clash-ipcidr:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/telegramip.mrs,86400
ruleset=🐦 Twitter,clash-domain:https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/twitter.mrs,86400
ruleset=🐦 Twitter,clash-ipcidr:https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/twitter.mrs,86400
ruleset=🎵 TikTok,clash-domain:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/tiktok.mrs,86400
ruleset=🪩 Cloudflare,clash-domain:https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cloudflare.mrs,86400
ruleset=🪟 Microsoft,clash-domain:https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.mrs,86400
ruleset=🍀 Google,clash-domain:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/gfw.mrs,86400
ruleset=🍀 Google,clash-domain:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/proxy.mrs,86400
ruleset=🎯 直连访问,clash-domain:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/cn.mrs,86400
ruleset=🎯 直连访问,clash-ipcidr:https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@mihomo-ruleset/cnip.mrs,86400
ruleset=🐟 漏网之鱼,[]FINAL

;策略组
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=♻️ 自动选择`url-test`.*`https://connectivitycheck.gstatic.com/generate_204`600,,50
custom_proxy_group=☁️ 故障转移`fallback`.*`https://connectivitycheck.gstatic.com/generate_204`600,,50
custom_proxy_group=🖲️ 手动选择`select`.*`[]DIRECT
custom_proxy_group=🔮 负载均衡`load-balance`.*`https://connectivitycheck.gstatic.com/generate_204`600,,50
custom_proxy_group=🍀 Google`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=🪩 Cloudflare`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=🪟 Microsoft`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=✈️ Telegram`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=🐦 Twitter`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问
custom_proxy_group=🎵 TikTok`select`[]🚀 节点选择`[]♻️ 自动选择`[]☁️ 故障转移`[]🔮 负载均衡`[]🖲️ 手动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇺🇳 其它地区`[]🎯 直连访问

custom_proxy_group=🇭🇰 香港节点`url-test`(?i)(港|hk|hongkong|hong kong|🇭🇰)`https://connectivitycheck.gstatic.com/generate_204`600,,50
custom_proxy_group=🇹🇼 台湾节点`url-test`(?i)(台|新北|彰化|tw|taiwan|🇹🇼)`https://connectivitycheck.gstatic.com/generate_204`600,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(?i)(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|jp|japan|🇯🇵)`https://connectivitycheck.gstatic.com/generate_204`600,,50
custom_proxy_group=🇺🇸 美国节点`url-test`(?i)(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|us|unitedstates|united states|🇺🇸)`https://connectivitycheck.gstatic.com/generate_204`600,,50
custom_proxy_group=🇸🇬 新加坡节点`url-test`(?i)(新加坡|坡|狮城|sg|singapore|🇸🇬)`https://connectivitycheck.gstatic.com/generate_204`600,,50
custom_proxy_group=🇺🇳 其它地区`url-test`(?i)(🇭🇰|🇹🇼|🇯🇵|🇺🇸|🇸🇬|🇨🇳|🇰🇷|港|hk|hongkong|台|新北|彰化|tw|taiwan|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|jp|japan|新加坡|坡|狮城|sg|singapore|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|us|united states)`https://connectivitycheck.gstatic.com/generate_204`600,,50

custom_proxy_group=🎯 直连访问`url-test`[]DIRECT`[]REJECT`https://connectivitycheck.platform.hicloud.com/generate_204`600
custom_proxy_group=🚫 拦截访问`select`[]REJECT`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]DIRECT`[]REJECT

;启用规则集
enable_rule_generator=false
overwrite_original_rules=false

;基础配置
clash_rule_base=https://cdn.jsdelivr.net/gh/some6508/run@master/store/mihomo.yaml
